version: '3.5'

services:
  psql:
    container_name: psql
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
  jdk11:
    container_name: jdk11
    build:
      context: .
      dockerfile: jdk11/Dockerfile
      args:
        - JAR_APP_FILE=${JAR_APP_FILE}
        - CONFIG_FILE=${CONFIG_FILE}
    ports:
      - "80:8080"
    depends_on:
      - psql

volumes:
  pgsql_data: